//! Word suggestions from a compact n-gram table built from `ainu-corpora`.
//!
//! The table (`data/ngrams.bin`, generated by `tools/build_ngrams.py` and
//! embedded via `include_bytes!`) holds:
//!   * a unigram frequency list (default / fallback suggestions), and
//!   * a bigram model: previous word → top-K likely next words.
//!
//! Words are canonical lowercase Latin (the IME's internal form); the candidate
//! UI converts them to katakana with `ainconv` for display.
//!
//! Binary layout (little-endian), matching `tools/build_ngrams.py`:
//! ```text
//! magic "AKNG" | u32 version
//! u32 n_uni  | n_uni × { u8 len, bytes, u32 count }
//! u32 n_ctx  | n_ctx × { u8 len, ctx, u8 k, k × { u8 len, word, u32 count } }
//! ```
//!
//! The parser is pure `std` (no `windows`), so it unit-tests on any host.
//!
//! The query API lands here ahead of its consumer (the candidate UI), so the
//! public items are not yet called from the IME flow.
#![allow(dead_code)]

use std::collections::HashMap;
use std::sync::OnceLock;

/// The embedded n-gram table.
const TABLE: &[u8] = include_bytes!("../data/ngrams.bin");
const MAGIC: &[u8; 4] = b"AKNG";

/// A parsed suggestion model.
pub struct Suggestions {
    /// Most-frequent words overall, descending by count.
    unigrams: Vec<(String, u32)>,
    /// Previous word → top next words (descending by count).
    bigrams: HashMap<String, Vec<(String, u32)>>,
}

/// Minimal forward byte reader; every read is bounds-checked and returns `None`
/// on a short/corrupt buffer so a bad table can never panic.
struct Reader<'a> {
    b: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn new(b: &'a [u8]) -> Self {
        Self { b, pos: 0 }
    }
    fn byte(&mut self) -> Option<u8> {
        let v = *self.b.get(self.pos)?;
        self.pos += 1;
        Some(v)
    }
    fn u32(&mut self) -> Option<u32> {
        let end = self.pos.checked_add(4)?;
        let s = self.b.get(self.pos..end)?;
        self.pos = end;
        Some(u32::from_le_bytes(s.try_into().ok()?))
    }
    fn take(&mut self, n: usize) -> Option<&'a [u8]> {
        let end = self.pos.checked_add(n)?;
        let s = self.b.get(self.pos..end)?;
        self.pos = end;
        Some(s)
    }
    /// A `u8`-length-prefixed UTF-8 string.
    fn string(&mut self) -> Option<String> {
        let len = self.byte()? as usize;
        let bytes = self.take(len)?;
        String::from_utf8(bytes.to_vec()).ok()
    }
}

impl Suggestions {
    /// Parse a table from raw bytes. Returns `None` if the bytes are not a
    /// valid table (wrong magic or truncated).
    pub fn load(bytes: &[u8]) -> Option<Self> {
        let mut r = Reader::new(bytes);
        if r.take(4)? != MAGIC {
            return None;
        }
        let _version = r.u32()?;

        let n_uni = r.u32()? as usize;
        let mut unigrams = Vec::with_capacity(n_uni);
        for _ in 0..n_uni {
            let w = r.string()?;
            let c = r.u32()?;
            unigrams.push((w, c));
        }

        let n_ctx = r.u32()? as usize;
        let mut bigrams = HashMap::with_capacity(n_ctx);
        for _ in 0..n_ctx {
            let ctx = r.string()?;
            let k = r.byte()? as usize;
            let mut nexts = Vec::with_capacity(k);
            for _ in 0..k {
                let w = r.string()?;
                let c = r.u32()?;
                nexts.push((w, c));
            }
            bigrams.insert(ctx, nexts);
        }

        Some(Self { unigrams, bigrams })
    }

    /// Likely next words after `prev`, highest-weight first. Empty if unknown.
    pub fn next_words(&self, prev: &str) -> &[(String, u32)] {
        self.bigrams.get(prev).map_or(&[], |v| v.as_slice())
    }

    /// The `n` most frequent words overall (default suggestions on empty input).
    pub fn default_words(&self, n: usize) -> &[(String, u32)] {
        &self.unigrams[..n.min(self.unigrams.len())]
    }

    /// Number of bigram contexts (for diagnostics/tests).
    pub fn context_count(&self) -> usize {
        self.bigrams.len()
    }
}

/// The process-wide table, parsed once from the embedded bytes. `None` only if
/// the embedded table is somehow corrupt (a build-time invariant).
pub fn global() -> Option<&'static Suggestions> {
    static G: OnceLock<Option<Suggestions>> = OnceLock::new();
    G.get_or_init(|| Suggestions::load(TABLE)).as_ref()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a tiny valid table in memory for parser tests (host-independent).
    fn synth() -> Vec<u8> {
        let mut b = Vec::new();
        b.extend(b"AKNG");
        b.extend(1u32.to_le_bytes());
        // 2 unigrams
        b.extend(2u32.to_le_bytes());
        for (w, c) in [("ne", 100u32), ("wa", 50)] {
            b.push(w.len() as u8);
            b.extend(w.as_bytes());
            b.extend(c.to_le_bytes());
        }
        // 1 context: "ruwe" -> [("ne", 17635)]
        b.extend(1u32.to_le_bytes());
        b.push(4);
        b.extend(b"ruwe");
        b.push(1); // k
        b.push(2);
        b.extend(b"ne");
        b.extend(17635u32.to_le_bytes());
        b
    }

    #[test]
    fn parses_synthetic_table() {
        let s = Suggestions::load(&synth()).expect("valid");
        assert_eq!(s.default_words(1)[0].0, "ne");
        assert_eq!(s.next_words("ruwe")[0], ("ne".to_string(), 17635));
        assert!(s.next_words("nope").is_empty());
    }

    #[test]
    fn rejects_garbage() {
        assert!(Suggestions::load(b"not a table").is_none());
        assert!(Suggestions::load(b"AKNG\x01").is_none()); // truncated
        assert!(Suggestions::load(&[]).is_none());
    }

    #[test]
    fn embedded_table_loads_and_predicts() {
        // Validates the real Python-generated table round-trips and that the
        // famous evidential collocation `ruwe ne` is the top prediction.
        let s = global().expect("embedded table parses");
        assert!(s.context_count() > 1000);
        let top = &s.next_words("ruwe")[0].0;
        assert_eq!(top, "ne", "after 'ruwe' the top next word should be 'ne'");
        assert!(!s.default_words(10).is_empty());
    }
}
