//! Word suggestions from a compact n-gram table built from `ainu-corpora`.
//!
//! The table (`data/ngrams.bin`, generated by `tools/build_ngrams.py` and
//! embedded via `include_bytes!`) holds:
//!   * a unigram frequency list (default / fallback suggestions),
//!   * a bigram model:  previous word         → top-K next words, and
//!   * a trigram model: (prev2 prev1) context → top-K next words.
//!
//! [`Suggestions::predict`] does trigram → bigram → (caller's unigram) backoff.
//! Words are canonical lowercase Latin (the IME's internal form); the candidate
//! UI converts them to katakana with `ainconv` for display.
//!
//! Binary layout (little-endian, version 2), matching `tools/build_ngrams.py`:
//! ```text
//! magic "AKNG" | u32 version
//! u32 n_uni | n_uni × { u8 len, bytes, u32 count }
//! <bigram section>   : u32 n | n × { u8 len, ctx, u8 k, k × { u8 len, word, u32 count } }
//! <trigram section>  : same shape; ctx is "prev2 prev1"
//! ```
//!
//! The parser is pure `std` (no `windows`), so it unit-tests on any host.
//!
//! The query API lands here ahead of its consumer (the candidate UI), so the
//! public items are not yet called from the IME flow.
#![allow(dead_code)]

use std::collections::HashMap;
use std::sync::OnceLock;

/// The embedded n-gram table.
const TABLE: &[u8] = include_bytes!("../data/ngrams.bin");
const MAGIC: &[u8; 4] = b"AKNG";

/// `context string → next words (descending by count)`.
type Contexts = HashMap<String, Vec<(String, u32)>>;

/// A parsed suggestion model.
pub struct Suggestions {
    /// Most-frequent words overall, descending by count.
    unigrams: Vec<(String, u32)>,
    /// Previous word → top next words.
    bigrams: Contexts,
    /// "prev2 prev1" → top next words.
    trigrams: Contexts,
}

/// Minimal forward byte reader; every read is bounds-checked and returns `None`
/// on a short/corrupt buffer so a bad table can never panic.
struct Reader<'a> {
    b: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn new(b: &'a [u8]) -> Self {
        Self { b, pos: 0 }
    }
    fn byte(&mut self) -> Option<u8> {
        let v = *self.b.get(self.pos)?;
        self.pos += 1;
        Some(v)
    }
    fn u32(&mut self) -> Option<u32> {
        let end = self.pos.checked_add(4)?;
        let s = self.b.get(self.pos..end)?;
        self.pos = end;
        Some(u32::from_le_bytes(s.try_into().ok()?))
    }
    fn take(&mut self, n: usize) -> Option<&'a [u8]> {
        let end = self.pos.checked_add(n)?;
        let s = self.b.get(self.pos..end)?;
        self.pos = end;
        Some(s)
    }
    /// A `u8`-length-prefixed UTF-8 string.
    fn string(&mut self) -> Option<String> {
        let len = self.byte()? as usize;
        String::from_utf8(self.take(len)?.to_vec()).ok()
    }
    /// A context section: `u32 count` followed by `ctx → [(word, count); k]`.
    fn contexts(&mut self) -> Option<Contexts> {
        let n = self.u32()? as usize;
        let mut map = HashMap::with_capacity(n);
        for _ in 0..n {
            let ctx = self.string()?;
            let k = self.byte()? as usize;
            let mut nexts = Vec::with_capacity(k);
            for _ in 0..k {
                let w = self.string()?;
                let c = self.u32()?;
                nexts.push((w, c));
            }
            map.insert(ctx, nexts);
        }
        Some(map)
    }
}

impl Suggestions {
    /// Parse a table from raw bytes. `None` if the bytes are not a valid table
    /// (wrong magic or truncated).
    pub fn load(bytes: &[u8]) -> Option<Self> {
        let mut r = Reader::new(bytes);
        if r.take(4)? != MAGIC {
            return None;
        }
        let _version = r.u32()?;

        let n_uni = r.u32()? as usize;
        let mut unigrams = Vec::with_capacity(n_uni);
        for _ in 0..n_uni {
            let w = r.string()?;
            let c = r.u32()?;
            unigrams.push((w, c));
        }

        let bigrams = r.contexts()?;
        let trigrams = r.contexts()?;
        Some(Self {
            unigrams,
            bigrams,
            trigrams,
        })
    }

    /// Likely next words after the single word `prev` (bigram). Empty if unknown.
    pub fn next_words(&self, prev: &str) -> &[(String, u32)] {
        self.bigrams.get(prev).map_or(&[], |v| v.as_slice())
    }

    /// Predict the next word with trigram → bigram backoff. Pass the two
    /// preceding words (`prev2` may be `None` at the start of input). Returns an
    /// empty slice if neither context is known (the caller may then fall back to
    /// [`default_words`](Self::default_words)).
    pub fn predict(&self, prev2: Option<&str>, prev1: &str) -> &[(String, u32)] {
        if let Some(p2) = prev2 {
            let key = format!("{p2} {prev1}");
            if let Some(v) = self.trigrams.get(&key) {
                return v.as_slice();
            }
        }
        self.next_words(prev1)
    }

    /// The `n` most frequent words overall (default suggestions on empty input).
    pub fn default_words(&self, n: usize) -> &[(String, u32)] {
        &self.unigrams[..n.min(self.unigrams.len())]
    }

    pub fn bigram_count(&self) -> usize {
        self.bigrams.len()
    }
    pub fn trigram_count(&self) -> usize {
        self.trigrams.len()
    }
}

/// The process-wide table, parsed once from the embedded bytes. `None` only if
/// the embedded table is somehow corrupt (a build-time invariant).
pub fn global() -> Option<&'static Suggestions> {
    static G: OnceLock<Option<Suggestions>> = OnceLock::new();
    G.get_or_init(|| Suggestions::load(TABLE)).as_ref()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn put_str(b: &mut Vec<u8>, s: &str) {
        b.push(s.len() as u8);
        b.extend(s.as_bytes());
    }
    fn put_ctx(b: &mut Vec<u8>, entries: &[(&str, &[(&str, u32)])]) {
        b.extend((entries.len() as u32).to_le_bytes());
        for (ctx, nexts) in entries {
            put_str(b, ctx);
            b.push(nexts.len() as u8);
            for (w, c) in *nexts {
                put_str(b, w);
                b.extend(c.to_le_bytes());
            }
        }
    }

    /// A tiny valid v2 table for host-independent parser tests.
    fn synth() -> Vec<u8> {
        let mut b = Vec::new();
        b.extend(b"AKNG");
        b.extend(2u32.to_le_bytes());
        // unigrams
        b.extend(2u32.to_le_bytes());
        for (w, c) in [("ne", 100u32), ("wa", 50)] {
            put_str(&mut b, w);
            b.extend(c.to_le_bytes());
        }
        // bigrams
        put_ctx(
            &mut b,
            &[("ruwe", &[("ne", 17635)]), ("ne", &[("na", 5522)])],
        );
        // trigrams
        put_ctx(&mut b, &[("ruwe ne", &[("na", 1200), ("wa", 900)])]);
        b
    }

    #[test]
    fn parses_synthetic_table() {
        let s = Suggestions::load(&synth()).expect("valid");
        assert_eq!(s.default_words(1)[0].0, "ne");
        assert_eq!(s.next_words("ruwe")[0], ("ne".to_string(), 17635));
        assert!(s.next_words("nope").is_empty());
        assert_eq!(s.bigram_count(), 2);
        assert_eq!(s.trigram_count(), 1);
    }

    #[test]
    fn predict_backs_off_trigram_to_bigram() {
        let s = Suggestions::load(&synth()).expect("valid");
        // Trigram hit: (ruwe, ne) -> na.
        assert_eq!(s.predict(Some("ruwe"), "ne")[0].0, "na");
        // No trigram for (foo, ruwe) -> back off to bigram of "ruwe" -> ne.
        assert_eq!(s.predict(Some("foo"), "ruwe")[0].0, "ne");
        // prev2 None -> bigram directly.
        assert_eq!(s.predict(None, "ruwe")[0].0, "ne");
        // Unknown everywhere -> empty (caller uses default_words).
        assert!(s.predict(Some("x"), "y").is_empty());
    }

    #[test]
    fn rejects_garbage() {
        assert!(Suggestions::load(b"not a table").is_none());
        assert!(Suggestions::load(b"AKNG\x02").is_none()); // truncated
        assert!(Suggestions::load(&[]).is_none());
    }

    #[test]
    fn embedded_table_loads_and_predicts() {
        // Validates the real Python-generated table round-trips.
        let s = global().expect("embedded table parses");
        assert!(s.bigram_count() > 1000);
        assert!(s.trigram_count() > 1000);
        assert_eq!(
            s.next_words("ruwe")[0].0,
            "ne",
            "after 'ruwe' the top next word should be 'ne'"
        );
        // Trigram context exists for the most common collocation.
        assert!(!s.predict(Some("ruwe"), "ne").is_empty());
        assert!(!s.default_words(10).is_empty());
    }
}
